<a href="https://colab.research.google.com/github/mani456256/INT213-K19PV-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
kanto = np.array([73, 67, 43])

In [ ]:
x = np.ones(5)

In [ ]:
x

array([1., 1., 1., 1., 1.])

In [ ]:
kanto

array([73, 67, 43])

In [ ]:
x = np.zeros([5,3])
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
x = np.array([[1,2],[2,3]])

In [ ]:
x[0][0]

1

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,6,7]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 6, 7]])

In [ ]:
x.max()


7

In [ ]:
import numpy as np
x = np.arange(4)
x

array([0, 1, 2, 3])

In [ ]:
y = x.reshape(2,2)

In [ ]:
y

array([[0, 1],
       [2, 3]])

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,1],[1,1]])
print(x,y)

[[1 2]
 [3 4]] [[1 1]
 [1 1]]


In [ ]:
np.add(x,y)


array([[2, 3],
       [4, 5]])

In [ ]:
np.subtract(x,y)

array([[0, 1],
       [2, 3]])

In [ ]:
np.power (x,2)

array([[ 1,  4],
       [ 9, 16]])

In [8]:
def AllCustomer(x):
  print("1gb for one month = ",x)
  def PortedCustomers(y):
    print("1GB for a month = ",y)
  return PortedCustomers

AllCustomer(256)(5)

1gb for one month =  256
1GB for a month =  5


In [9]:
##memoization
x = memoryview(b'\x55')
x

In [10]:
class MyClass:
  x =5

print(MyClass)  

<class '__main__.MyClass'>


In [11]:
class MyClass:
  x =5
p1 = MyClass()
print(p1.x)  

5


In [12]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age
p1 = Person("John",36)     

In [14]:
print(p1.name)
print(p1.age)

John
36


In [17]:
class Person:
  def __init__(self,name,age):
    self.name = name
    self.age = age
  def myfunc(self):
    print("Hello my name is  ",self.name)
p1 =Person("john",36)
p1.myfunc()      

Hello my name is   john


In [18]:
p1 = Person("Jhon",36)
p2 = Person("Adam",23)
print(p1.age)
print(p2.age)

36
23


In [19]:
del p1.age

In [20]:
p1.age

AttributeError: ignored

In [22]:
try:
  print(ABs)
except NameError:
  print("Variable x is not defined")
except:
  print("Something else went wrong")    

Variable x is not defined


In [23]:
try: 
  y = 3/0
except ZeroDivisionError as err:
  print("Handling run-time error:", err)  

Handling run-time error: division by zero


In [25]:
try:
  x = input("Enter number: ")
  x = x+1
  print(x)
except:
  print("Invalid input")  

Enter number: 8
Invalid input


In [26]:
x = 45

if x< 0:
  raise Exception("Sorry, no number below zero")

In [27]:
x = 10