<a href="https://colab.research.google.com/github/mani456256/INT213-K19PV-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
kanto = np.array([73, 67, 43])

In [ ]:
x = np.ones(5)

In [ ]:
x

array([1., 1., 1., 1., 1.])

In [ ]:
kanto

array([73, 67, 43])

In [ ]:
x = np.zeros([5,3])
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
x = np.array([[1,2],[2,3]])

In [ ]:
x[0][0]

1

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,6,7]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 6, 7]])

In [ ]:
x.max()


7

In [ ]:
import numpy as np
x = np.arange(4)
x

array([0, 1, 2, 3])

In [ ]:
y = x.reshape(2,2)

In [ ]:
y

array([[0, 1],
       [2, 3]])

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,1],[1,1]])
print(x,y)

[[1 2]
 [3 4]] [[1 1]
 [1 1]]


In [ ]:
np.add(x,y)


array([[2, 3],
       [4, 5]])

In [ ]:
np.subtract(x,y)

array([[0, 1],
       [2, 3]])

In [ ]:
np.power (x,2)

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
def AllCustomer(x):
  print("1gb for one month = ",x)
  def PortedCustomers(y):
    print("1GB for a month = ",y)
  return PortedCustomers

AllCustomer(256)(5)

1gb for one month =  256
1GB for a month =  5


In [ ]:
##memoization
x = memoryview(b'\x55')
x

In [ ]:
class MyClass:
  x =5

print(MyClass)  

<class '__main__.MyClass'>


In [ ]:
class MyClass:
  x =5
p1 = MyClass()
print(p1.x)  

5


In [ ]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age
p1 = Person("John",36)     

In [ ]:
print(p1.name)
print(p1.age)

John
36


In [ ]:
class Person:
  def __init__(self,name,age):
    self.name = name
    self.age = age
  def myfunc(self):
    print("Hello my name is  ",self.name)
p1 =Person("john",36)
p1.myfunc()      

Hello my name is   john


In [ ]:
p1 = Person("Jhon",36)
p2 = Person("Adam",23)
print(p1.age)
print(p2.age)

36
23


In [ ]:
del p1.age

In [ ]:
p1.age

AttributeError: ignored

In [ ]:
try:
  print(ABs)
except NameError:
  print("Variable x is not defined")
except:
  print("Something else went wrong")    

Variable x is not defined


In [ ]:
try: 
  y = 3/0
except ZeroDivisionError as err:
  print("Handling run-time error:", err)  

Handling run-time error: division by zero


In [ ]:
try:
  x = input("Enter number: ")
  x = x+1
  print(x)
except:
  print("Invalid input")  

Enter number: 8
Invalid input


In [ ]:
x = 45

if x< 0:
  raise Exception("Sorry, no number below zero")

In [ ]:
x = 10

In [ ]:
from tables import Column
import pandas as pd
import matplotlib.pyplot as plt
import math

Data = {'A': [4,2,2,1,8,6,9,8,11,13,12,14],
        'B': [1,2,2,4,9,8,9,6,14,12,13,12],
        'Z': [1,2,3,4,1,2,3,4,1,2,3,4]}
df = pd.DataFrame(Data,columns =['A','B','Z'])
df        

A   B  Z
0    4   1  1
1    2   2  2
2    2   2  3
3    1   4  4
4    8   9  1
5    6   8  2
6    9   9  3
7    8   6  4
8   11  14  1
9   13  12  2
10  12  13  3
11  14  12  4

In [ ]:
!pip install pingouin

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.6/198.6 KB 8.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 79.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for littleutils: filename=littleutils-0.2.2-py3-none-any.whl size=7047 sha256=19ae07f18906248749b2b991e3c1b95730f0dd41f898e4bb4e24f5203725d8b6
  Stored in directory: /root/.cache/pip/wheels/6a/33/c4/0ef84d7f5568c2823e3d63a6e08988852fb9e4bc822034870a
Successfully built littleutils
  Attempting uninstall: statsmodels
    Found existing installation: statsmodels 0.12.2
    Uninstalling statsmodels-0.12.2:
      Successfully uninstalled statsmodels-0.12.2


In [ ]:
import pingouin as pg
pg.partial_corr(data = df, x = 'A',y = 'B', covar = 'Z')

n         r         CI95%     p-val
pearson  12  0.910789  [0.69, 0.98]  0.000097

In [ ]:
from scipy.stats import ttest_1samp
import numpy as np

In [ ]:
ages = [45,89,55,33,35,23,34,65,12,54,34]
print(ages)

[45, 89, 55, 33, 35, 23, 34, 65, 12, 54, 34]


In [ ]:
t_test, p_val = ttest_1samp(ages,45)
print("P-value is:", p_val)

P-value is: 0.8256830046763577


In [1]:
class A:
  def __init__(self,n):
    self.name = n
  
class B(A):
  def __init__(self, roll):
    self.roll = roll

X = B(23)
print(X.roll)

23


In [2]:
class Animal:
  def speak (self):
    print("Animal Speaking")

class Dog(Animal):
  def bark(self):
    print("dog barking")

d = Dog()
d.bark()
d.speak()

dog barking
Animal Speaking


In [5]:
class Animal:
  def speak (self):
    print("Animal Speaking")

class Dog(Animal):
  def bark(self):
    print("dog barking")

class Dogchild(Dog):
  def eat(self):
    print("Eating breeaddddd.........")

d = Dogchild()
d.bark()
d.speak()
d.eat()

dog barking
Animal Speaking
Eating breeaddddd.........


In [19]:
class A:
  def sum(self,a,b):
    return a+b;
class B:
  def sub(self,a,b):
    return a-b;
class C(A,B):
  def mul(self,a,b):
    return a*b

x = C()
print(x.sum(2,3))
print(x.sub(2,5))
print(x.mul(3,5))

5
-3
15


In [20]:
class Person(object):
  def __init__(self,name, idnumber):
    self.name = name
    self.idnumber = idnumber

  def display(self):
    print(self.name) 
    print(self.idnumber)
class Employee(Person):
  def __init__(self,name,idnumber,salary,post):
    self.salary = salary 
    Person.__init__(self,name,idnumber)

a = Employee('rahul',88892,911111,"Intern")
a .display()        

rahul
88892


In [21]:
class Animal():
  def eat(self):
    print("I can eat")

class Dog(Animal):
  def eat(self):
    print("I like to eat bones")    

labrador = Dog()
labrador.eat()    

I like to eat bones


In [23]:
class Animal():
  def eat(self):
    print("I can eat")

class Dog(Animal):
  def eat(self):
    super().eat()
    print("I like to eat bones")    

labrador = Dog()
labrador.eat()    

I can eat
I like to eat bones


In [29]:
import sqlite3

conn = sqlite3.connect('Comapny')
print("A new Databaedkfhlksjf")

conn.execute('''CREATE TABLE COMPANYs(ID INT,NAME TEXT);''')
print("A new Database is creted")
conn.close()

A new Databaedkfhlksjf
A new Database is creted


In [30]:
import sqlite3

 
X = sqlite3.connect('NeDB.db')
 
Y = X.cursor()

 
Y.execute('''CREATE TABLE IF NOT EXISTS EMPLOYEE (
         	ID integer,
         	Name text NOT NULL,
         	Date_Join text,
            Place text,
            Salary integer,
            Age real);''')

 
Y.execute("INSERT INTO Employee VALUES (1,'John','2020-01-01','Kerala',32,25000)")
 
X.commit()

Y.close()

In [31]:
import sqlite3

 
X = sqlite3.connect('MAnus.db')
 
Y = X.cursor()

 
Y.execute('''CREATE TABLE IF NOT EXISTS EMPLOYEE (
         	ID integer,
         	Name text NOT NULL,
         	Date_Join text,
            Place text,
            Salary integer,
            Age real);''')

 
Y.execute("INSERT INTO Employee VALUES (1,'John','2020-03-01','Kerala',32,25000),(2,'Adam','2020-01-01','TN',22,30000),(3,'Mary','2022-01-01','Karnataka',24,120000)")

for row in Y.execute('SELECT * FROM Employee ORDER BY Date_Join'):
        print(row)

        
X.commit()

Y.close()

(2, 'Adam', '2020-01-01', 'TN', 22, 30000.0)
(1, 'John', '2020-03-01', 'Kerala', 32, 25000.0)
(3, 'Mary', '2022-01-01', 'Karnataka', 24, 120000.0)


In [52]:
import sqlite3

 
X = sqlite3.connect('mfsdfghj.db')
 
Y = X.cursor()

 
Y.execute('''CREATE TABLE IF NOT EXISTS EMPLOYEE (
         	ID integer,
         	Name text NOT NULL,
         	Date_Join text,
            Place text,
            Salary real,
            Age real);''')

 
Y.execute("INSERT INTO Employee VALUES (1,'John','2020-03-01','Kerala',32,25000),(2,'Adam','2020-01-01','TN',22,30000),(3,'Mary','2022-01-01','Karnataka',24,120000)")

A = 'John'
Y.execute("SELECT * FROM Employee WHERE Age > 50000 and Salary < 23")
Y.execute("SELECT * FROM Employee WHERE Name LIKE 'j%'")
Y.execute("SELECT * FROM Employee WHERE Salary IN (25,32)")
Y.execute("SELECT * FROM Employee WHERE Name LIKE 'j%'")

print(Y.fetchall())

        
X.commit()

Y.close()

[(1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0), (1, 'John', '2020-03-01', 'Kerala', 32, 25000.0)]


In [5]:
a = [2,5,6,3,8,4]
a.sort()
a

[2, 3, 4, 5, 6, 8]

In [6]:
def selectionSort(array, size):
	
	for ind in range(size):
		min_index = ind

		for j in range(ind + 1, size):
			if array[j] < array[min_index]:
				min_index = j
		(array[ind], array[min_index]) = (array[min_index], array[ind])

arr = [-2, 45, 0, 11, -9,88,-97,-202,747]
size = len(arr)
selectionSort(arr, size)
print('The array after sorting in Ascending Order by selection sort is:')
print(arr)


The array after sorting in Ascending Order by selection sort is:
[-202, -97, -9, -2, 0, 11, 45, 88, 747]


In [9]:
def bubbleSort(arr):
	n = len(arr)
	swapped = False
	for i in range(n-1):
		for j in range(0, n-i-1):
			if arr[j] > arr[j + 1]:
				swapped = True
				arr[j], arr[j + 1] = arr[j + 1], arr[j]
arr = [64, 34, 25, 12, 22, 11, 90]
bubbleSort(arr)
print("Sorted array is:")
for i in range(len(arr)):
	print("% d" % arr[i], end=" ")

Sorted array is:
 11  12  22  25  34  64  90 

In [14]:
def bubbleSort(list1):
  for i in range (0,len(list1)-1):
    for j in range(len(list1)-1):
      if (list1[j]>list1[j+1]):
        temp = list1[j]
        list1[j]= list1[j+1]
        list1[j+1] = temp
  return list1        
list1 = [8,6,5,6,44,3,2,22]
print("the unsirted list : ",list1) 
print(bubbleSort(list1))  

the unsirted list :  [8, 6, 5, 6, 44, 3, 2, 22]
[2, 3, 5, 6, 6, 8, 22, 44]


In [15]:
def insertionSort(array):

    for step in range(1, len(array)):
        key = array[step]
        j = step - 1
        while j >= 0 and key < array[j]:
            array[j + 1] = array[j]
            j = j - 1
        array[j + 1] = key


data = [9, 5, 1, 4, 3]
insertionSort(data)
print('Sorted Array in Ascending Order:')
print(data)

Sorted Array in Ascending Order:
[1, 3, 4, 5, 9]


In [16]:
def mergeSort(arr):
	if len(arr) > 1:
		mid = len(arr)//2
		L = arr[:mid]
		R = arr[mid:]
		mergeSort(L)
		mergeSort(R)
		i = j = k = 0
		while i < len(L) and j < len(R):
			if L[i] <= R[j]:
				arr[k] = L[i]
				i += 1
			else:
				arr[k] = R[j]
				j += 1
			k += 1
		while i < len(L):
			arr[k] = L[i]
			i += 1
			k += 1

		while j < len(R):
			arr[k] = R[j]
			j += 1
			k += 1

def printList(arr):
	for i in range(len(arr)):
		print(arr[i], end=" ")
	print()

if __name__ == '__main__':
	arr = [12, 11, 13, 5, 6, 7]
	print("Given array is", end="\n")
	printList(arr)
	mergeSort(arr)
	print("Sorted array is: ", end="\n")
	printList(arr)


Given array is
12 11 13 5 6 7 
Sorted array is: 
5 6 7 11 12 13 


In [17]:
def partition(array, low, high):
	pivot = array[high]
	i = low - 1
	for j in range(low, high):
		if array[j] <= pivot:
			i = i + 1
			(array[i], array[j]) = (array[j], array[i])
	(array[i + 1], array[high]) = (array[high], array[i + 1])
	return i + 1
def quick_sort(array, low, high):
	if low < high:
		pi = partition(array, low, high)
		quick_sort(array, low, pi - 1)
		quick_sort(array, pi + 1, high)
array = [10, 7, 8, 9, 1, 5]
quick_sort(array, 0, len(array) - 1)

print(f'Sorted array: {array}')

Sorted array: [1, 5, 7, 8, 9, 10]


In [20]:
def linearSearch (array,n,x):
  for i in range (0,n):
    if (array[i]==x):
      return 1
  return -1    

array = [2,3,0 ,1,9]
x = 1
n = len(array)
result = linearSearch(array,n,x)
if(result == -1):
  print("element not found")
else:
  print("elemnet is found") 

elemnet is found


In [21]:
def binary_search(arr, low, high, x):
	if high >= low:
		mid = (high + low) // 2
		if arr[mid] == x:
			return mid

		elif arr[mid] > x:
			return binary_search(arr, low, mid - 1, x)
		else:
			return binary_search(arr, mid + 1, high, x)
	else:
		return -1
arr = [ 2, 3, 4, 10, 40 ]
x = 10
result = binary_search(arr, 0, len(arr)-1, x)

if result != -1:
	print("Element is present at index", str(result))
else:
	print("Element is not present in array")


Element is present at index 3


In [23]:
import threading
def print_cube(num):
	print("Cube: {}" .format(num * num * num))
def print_square(num):
	print("Square: {}" .format(num * num))
if __name__ =="__main__":
	t1 = threading.Thread(target=print_square, args=(10,))
	t2 = threading.Thread(target=print_cube, args=(10,))
	t1.start()
	t2.start()
	t1.join()
	t2.join()
	print("Done!")


Square: 100
Cube: 1000
Done!
